### ISSUE TITLE
Execute

### ISSUE THREAD

**Issue by gabrielbuzziv** [kristoffer-tvera/mute-current-application#1]
How i'm supposed to execute this?

**Comment by kristoffer-tvera** [comment]
Through AutoHotkey. The files are script files that AHK will recognize.
https://autohotkey.com/

There is also a release for windows (.exe) available.
https://github.com/bzl/mute-current-application/releases

**Comment by b3njiiiiii** [comment]
yoooooooooooooooooooooo how do i turn it off
