### ISSUE TITLE
There was a problem retrieving the application volume interface 

### ISSUE THREAD

**Issue by Schweiger-Jacob** [kristoffer-tvera/mute-current-application#12]
this is what it says when I try to use the hotkey

**Comment by PedroHorace** [comment]
Yes same here. Waiting for a solution.

**Comment by tfourj** [comment]
I just opened [PR](https://github.com/kristoffer-tvera/mute-current-application/pull/14) that should fix the issues you guys had.
In the meantime you can test it from my repo and let me know if you have any issues

**Comment by kristoffer-tvera** [comment]
> I just opened [PR](https://github.com/kristoffer-tvera/mute-current-application/pull/14) that should fix the issues you guys had. In the meantime you can test it from my repo and let me know if you have any issues

PR approved, sorry for the holdup.
