### ISSUE TITLE
plzzzz help me i cant hear anything

### ISSUE THREAD

**Issue by b3njiiiiii** [kristoffer-tvera/mute-current-application#3]
i pressed F1 and it muted it but i pressed F1 again to turn it off and now it just brings me to google help and i cant hear anything i am getting really mad plz help me

**Comment by kristoffer-tvera** [comment]
It uses the windows volume mixer(speaker icon in system tray next to clock). Open that and modify to your liking.

**Comment by b3njiiiiii** [comment]
thank to sooo much
