### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by PatrickLTI** [kristoffer-tvera/mute-current-application#4]
Hello, thanks for writing this script. How would I go about installing these files? Could you do a quick step instructions? Thanks again!

**Comment by kristoffer-tvera** [comment]
There is no installer. You should be fine by downloading the exe found inside "[Releases](https://github.com/kristoffer-tvera/mute-current-application/releases)". After that, clicking it should open a green icon in your system tray (with a white H inside it). That indicates that it is running, and F1 will now be muting your current fullscreen program.

If you find that you use this a lot, you could put this program in the startup-folder. This comes at the cost of some seconds on your boot time, at the tradeoff that you no longer have to manually initiate it any more. 

The first link covers Windows 7, Windows 8, Windows 8.1
The second link covers Windows 10.

https://www.howtogeek.com/208224/how-to-add-programs-files-and-folders-to-system-startup-in-windows-8.1/

https://social.technet.microsoft.com/Forums/en-US/f0005629-0377-4e4b-82cc-26aff7b95884/how-do-you-add-new-startup-programs-in-wndows-10?forum=WinPreview2014General


Let me know below how you do, and I'll get back to you.

**Comment by PatrickLTI** [comment]
Thank you so much for this. I will try it out now and let you know tonight. 
Regards,
Pat

**Comment by PatrickLTI** [comment]
Is there anyway I can mute only the airplane and not all audio in-game? I don't know if PUBG would consider that cheating or not. I have volume adjustment on my headphones, but wanted something that could block a specific sound without changing the volume for the rest of the game.

**Comment by kristoffer-tvera** [comment]
This would be possible, but would definitively be considered cheating.

**Comment by PatrickLTI** [comment]
Shucks, I'll have to manually adjust the volume then. Your script works perfectly. Thanks again.
