### ISSUE TITLE
Can mute be reassigned to 'duck' or lower audio to say 25%

### ISSUE THREAD

**Issue by Formyndare** [kristoffer-tvera/mute-current-application#5]
I feel this would be a great option to have. Sometimes you don't wish to fully mute a program but just lower the volume quickly.

**Comment by kristoffer-tvera** [comment]
I could forseeably make a "stepping" keybind that increments master volume by 10% on a keybind.

Also, changing keybind is quite simple, and the readme has some text on exactly how you would go about that. If you dont feel comfortable compiling an AHK script, post back and I can compile a exe for you with a given keybinding for mute.
