### ISSUE TITLE
Script broken with Windows 10 2018 Spring Update

### ISSUE THREAD

**Issue by develogix** [kristoffer-tvera/mute-current-application#6]
The script no longer works with the 2018 Spring update for Windows 10.

**Comment by kristoffer-tvera** [comment]
I'm running Windows 10 Version 1803 (April/Spring update), and it works. Explain what programs you are trying to mute, and/or what steps you have taken when trying to make this work, and I will be better able to help you.

**Comment by develogix** [comment]
I just realized that I updated the script, and did not rebind it to the same key that I had previously used.
